### PR TITLE
Updated cancel-uploads-button click event logic to properly remove all s...

### PR DESCRIPTION
**Pull request by dogeared**
...taged files.

### CODE REVIEW

**Comment by sroze** [comment]
`self.files.at(0).cancel()` automatically remove file from `self.files` collection ?!

**Comment by dogeared** [comment]
I was working from this issue: https://github.com/sroze/backbone-upload-manager/issues/7

Seemed like a good approach. Am I missing something?

**Comment by dogeared** [comment]
wanted to ping on this. Does this solution work for you?

**Comment by sroze** [comment]
It's suitable, thanks !

**Pull request merged**
